"""update parent-child relationships

Revision ID: d6d0667d3a3d
Revises: caab820f685b
Create Date: 2026-07-28 17:08:16.177709

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd6d0667d3a3d'
down_revision: str | Sequence[str] | None = 'caab820f685b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_owner_id_fkey'), 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_member_project_id_fkey'), 'project_member', type_='foreignkey')
    op.drop_constraint(op.f('project_member_user_id_fkey'), 'project_member', type_='foreignkey')
    op.create_foreign_key(None, 'project_member', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_member', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('task', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('task_assigned_to_fkey'), 'task', type_='foreignkey')
    op.drop_constraint(op.f('task_assigned_by_fkey'), 'task', type_='foreignkey')
    op.drop_constraint(op.f('task_project_id_fkey'), 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'task', 'user', ['assigned_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key(op.f('task_project_id_fkey'), 'task', 'project', ['project_id'], ['id'])
    op.create_foreign_key(op.f('task_assigned_by_fkey'), 'task', 'user', ['assigned_by'], ['id'])
    op.create_foreign_key(op.f('task_assigned_to_fkey'), 'task', 'user', ['assigned_to'], ['id'])
    op.alter_column('task', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'project_member', type_='foreignkey')
    op.drop_constraint(None, 'project_member', type_='foreignkey')
    op.create_foreign_key(op.f('project_member_user_id_fkey'), 'project_member', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('project_member_project_id_fkey'), 'project_member', 'project', ['project_id'], ['id'])
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key(op.f('project_owner_id_fkey'), 'project', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
